import type { Metadata } from "next";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className='min-h-screen, w-full flex'>
			<SideBar />
			<div className='w-full p-8'>{children}</div>
		</div>
	);
}
